### ISSUE TITLE
Assistant metadata not stored

### ISSUE THREAD

**Issue by CakeCrusher** [stellar-amenities/assistants#50]
After creating an assistant with metadata the returned assistant does not contain that metadata.
code:
```py
def create_assistant():
    assistant = openai.beta.assistants.create(
        instructions="You are a weather bot. Use the provided functions to answer questions.",
        model="gpt-3.5-turbo-1106",
        name="Weather Bot",
        metadata={
            "openapi_spec": "https://raw.githubusercontent.com/openai/mini-api/master/examples/weather/weather.yaml"
        },
        tools=[{
            "type": "function",
            "function": {
                "name": "getCurrentWeather",
                "description": "Get the weather in location",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "location": { "type": "string", "description": "The city and state e.g. San Francisco, CA" },
                        "unit": { "type": "string" }
                    },
                    "required": ["location"]
                }
            }
        }]
    )
    print("CREATING ASSISTANT: ", model_to_json_str(assistant))
    return assistant
create_assistant()
```
response:
```sh
CREATING ASSISTANT:  {
    "id": "09c821f0-a4dd-4c08-979f-df63448b2627",
    "created_at": 1704407771,
    "description": null,
    "file_ids": [],
    "instructions": "You are a weather bot. Use the provided functions to answer questions.",
    "metadata": null,
    "model": "gpt-3.5-turbo-1106",
    "name": "Weather Bot",
    "object": "",
    "tools": [
        {
            "function": {
                "name": "getCurrentWeather",
                "description": "Get the weather in location",
                "parameters": {
                    "properties": {
                        "location": {
                            "description": "The city and state e.g. San Francisco, CA",
                            "type": "string"
                        },
                        "unit": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "location"
                    ],
                    "type": "object"
                }
            },
            "type": "function"
        }
    ]
}
```

I am happy to contribute the fix @louis030195 , if you could guide me as to where I should look to resolve this and other considerations that would help a ton.

**Comment by louis030195** [comment]
@CakeCrusher ow thanks a lot! Indeed it's not implemented at all, to implement it I would:

1. [read the migration file](https://github.com/stellar-amenities/assistants/blob/0531bfda4b5124efb8fd36b87da81c6d80e89c6b/assistants-core/src/migrations.sql#L20)
2. [add the metadata in the create assistant query](https://github.com/stellar-amenities/assistants/blob/0531bfda4b5124efb8fd36b87da81c6d80e89c6b/assistants-core/src/assistants.rs#L136)
3. [make sure the api part properly pass the metadata from the client query](https://github.com/stellar-amenities/assistants/blob/0531bfda4b5124efb8fd36b87da81c6d80e89c6b/assistants-api-communication/src/assistants.rs#L47) 
4. create a unit test that check that upon creating an assistant you properly have the metadata stored [here](https://github.com/stellar-amenities/assistants/blob/main/assistants-api-communication/src/assistants.rs#L47) or at the end of [here](https://github.com/stellar-amenities/assistants/blob/main/assistants-api-communication/src/main.rs) (pref first location if you manage to do it, otherwise it's k in the main.rs but 2.4k lines start to be a bit too much).
5. make sure postgres run locally (`make reboot`) & run `cargo sqlx prepare --workspace` (required every time to change a query or migrations)
6. send PR

i think that's it

Appreciate a lot contributions! Let's make it easy to have fast, cheap, data private, open assistants :)

**Comment by CakeCrusher** [comment]
@louis030195 
The create portion is ready to go. Im not sure if you added the right links on 4 so please verify those, but everything else is checked.
